// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8sILXEINHspFiVFWbVssG9csPgPxkYoc',
    appId: '1:1025629629452:web:196129050022c16181d229',
    messagingSenderId: '1025629629452',
    projectId: 'asistant-231c2',
    authDomain: 'asistant-231c2.firebaseapp.com',
    databaseURL: 'https://asistant-231c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'asistant-231c2.appspot.com',
    measurementId: 'G-4M3XFF6SSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUNIeqvVEubFl2feK576JimNeAz8Ol4Ts',
    appId: '1:1025629629452:android:dd81a63c5f8bb84381d229',
    messagingSenderId: '1025629629452',
    projectId: 'asistant-231c2',
    databaseURL: 'https://asistant-231c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'asistant-231c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjmGgCxZ8CgB9wiEFinCEQjpnZ7uMc4AU',
    appId: '1:1025629629452:ios:cfca835b7a74cdcd81d229',
    messagingSenderId: '1025629629452',
    projectId: 'asistant-231c2',
    databaseURL: 'https://asistant-231c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'asistant-231c2.appspot.com',
    androidClientId: '1025629629452-hf23jkvu7ch9hdj38ktvavva6uc39pql.apps.googleusercontent.com',
    iosClientId: '1025629629452-97651td6i3kmv2fra341qulmd2edjkil.apps.googleusercontent.com',
    iosBundleId: 'com.example.appasistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjmGgCxZ8CgB9wiEFinCEQjpnZ7uMc4AU',
    appId: '1:1025629629452:ios:cfca835b7a74cdcd81d229',
    messagingSenderId: '1025629629452',
    projectId: 'asistant-231c2',
    databaseURL: 'https://asistant-231c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'asistant-231c2.appspot.com',
    androidClientId: '1025629629452-hf23jkvu7ch9hdj38ktvavva6uc39pql.apps.googleusercontent.com',
    iosClientId: '1025629629452-97651td6i3kmv2fra341qulmd2edjkil.apps.googleusercontent.com',
    iosBundleId: 'com.example.appasistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8sILXEINHspFiVFWbVssG9csPgPxkYoc',
    appId: '1:1025629629452:web:6766ed790d3110f181d229',
    messagingSenderId: '1025629629452',
    projectId: 'asistant-231c2',
    authDomain: 'asistant-231c2.firebaseapp.com',
    databaseURL: 'https://asistant-231c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'asistant-231c2.appspot.com',
    measurementId: 'G-ZVVC05V73K',
  );

}